### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by TheRealKingslayer51** [Stereowalker/C.O.M.B.A.T.#1]
I don't know if there is something that I did wrong, but every time I get into the game and load up a world, the game proceeds to crash. I usually don't have this issue and this issue does not occur whenever I load a world without the C.O.M.B.A.T. mod active.

This is the crash report:
Description: Unexpected error

java.lang.ExceptionInInitializerError: null
	at com.stereowalker.combat.world.WorldEvents.entityJoinWorld(WorldEvents.java:199) ~[?:1.14.3-0.8.0] {}
	at net.minecraftforge.eventbus.ASMEventHandler_26_WorldEvents_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.2-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.2-service.jar:?] {}
	at net.minecraft.client.world.ClientWorld.func_217424_b(ClientWorld.java:272) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217408_a(ClientWorld.java:263) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:357) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:76) ~[?:?] {}
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:13) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil$$Lambda$4289/1817198044.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:99) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:856) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:154) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.3-27.0.23.jar:27.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$313/1332691311.call(Unknown Source) [forge-1.14.3-27.0.23.jar:27.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-2.1.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-2.1.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77) [modlauncher-2.1.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:62) [modlauncher-2.1.5.jar:?] {}
Caused by: com.stereowalker.combat.client.renderer.entity.cape.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.client.entity.player.AbstractClientPlayerEntity.getPlayerInfo()
	at com.stereowalker.combat.client.renderer.entity.cape.ReflectionHelper.findMethod(ReflectionHelper.java:236) ~[?:1.14.3-0.8.0] {}
	at com.stereowalker.combat.client.renderer.entity.cape.ReflectionUtil.findMethod(ReflectionUtil.java:27) ~[?:1.14.3-0.8.0] {}
	at com.stereowalker.combat.client.renderer.entity.cape.Cape.<clinit>(Cape.java:30) ~[?:1.14.3-0.8.0] {}
	... 29 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.client.entity.player.AbstractClientPlayerEntity.getPlayerInfo()
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_51] {}
	at com.stereowalker.combat.client.renderer.entity.cape.ReflectionHelper.findMethod(ReflectionHelper.java:230) ~[?:1.14.3-0.8.0] {}
	at com.stereowalker.combat.client.renderer.entity.cape.ReflectionUtil.findMethod(ReflectionUtil.java:27) ~[?:1.14.3-0.8.0] {}
	at com.stereowalker.combat.client.renderer.entity.cape.Cape.<clinit>(Cape.java:30) ~[?:1.14.3-0.8.0] {}
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.stereowalker.combat.world.WorldEvents.entityJoinWorld(WorldEvents.java:199)
	at net.minecraftforge.eventbus.ASMEventHandler_26_WorldEvents_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.world.ClientWorld.func_217424_b(ClientWorld.java:272)
	at net.minecraft.client.world.ClientWorld.func_217408_a(ClientWorld.java:263)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:357)
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:76)
	at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:13)
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil$$Lambda$4289/1817198044.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 625, 0
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$313/1332691311.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:62)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1260242032 bytes (1201 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.14.3-forge-27.0.23
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13467 Compatibility Profile Context 21.19.414.1280, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 2x AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G

**Comment by Stereowalker** [comment]
The error had something to do with the capes of version 1.14.3-0.8.0 and below. I fixed the bug in 1.14.3-0.9.0 I suggest you download that version and above
