### ISSUE TITLE
Hypothermia

### ISSUE THREAD

**Issue by poboy975** [Stereowalker/C.O.M.B.A.T.#3]
Hi, I can' turn of hypothermia. I've set the server.toml file to false on temp, but the client.toml is empty. When I tried to copy/paste the temp from server to client, it vanishes everytime I start minecraft. And the temp in the nether isn't changing. It's still killing me.

**Comment by Stereowalker** [comment]
Check the server config for your world

**Comment by MyTh-Vestarion** [comment]
Hey, can't get the mod to load without crashing. Don't know if this extract from the log helps?



 [modloading-worker-2/ERROR]: Failed to create mod instance. ModID: combat, class com.stereowalker.combat.Combat
java.lang.NoSuchMethodError: net.minecraft.block.Block$Properties.harvestTool(Lnet/minecraftforge/common/ToolType;)Lnet/minecraft/block/Block$Properties;
	at com.stereowalker.combat.lists.CBlocks.<clinit>(CBlocks.java:54) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.world.gen.feature.AusldineTreeFeature.<clinit>(AusldineTreeFeature.java:21) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.world.gen.feature.FeatureList.<clinit>(FeatureList.java:13) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.world.biome.CombatBiomeFeatures.addDeadTrees(CombatBiomeFeatures.java:29) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.world.biome.DeadForestBiome.<init>(DeadForestBiome.java:31) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.lists.CBiomes.<clinit>(CBiomes.java:15) ~[?:1.14.3-0.10.0]
	at com.stereowalker.combat.Combat.<init>(Combat.java:67) ~[?:1.14.3-0.10.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:27.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$1950/934651164.accept(Unknown Source) [?:27.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1949/438248178.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1949/438248178.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:119) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2040/340296488.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by Stereowalker** [comment]
What version of forge are you using

**Comment by MyTh-Vestarion** [comment]
27.0.23

**Comment by Stereowalker** [comment]
@MyTh-Vestarion update forge to 27.0.30 to get it to work

**Comment by Stereowalker** [comment]
@poboy975 the server config is in your worlds saves. Check for a "serverconfig" folder
