### ISSUE TITLE
Keep getting this crash

### ISSUE THREAD

**Issue by Trinova1** [Stereowalker/C.O.M.B.A.T.#7]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Redundant texture list for particle combat:acrotlest_portal

Full report 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/27/19 7:46 PM
Description: Rendering overlay

java.lang.IllegalStateException: Redundant texture list for particle combat:acrotlest_portal
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:202) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:154) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager$$Lambda$2580/617400603.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/701487403.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1793308656 bytes (1710 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.82.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.82.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.82.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.82.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.82.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.82
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		BasicNetherOres-1.14.4-3.2.2.jar Basic Nether Ores {bno@3.2.2 ENQUEUE_IMC}
		C.O.M.B.A.T.-1.14.4-0.21.0.jar C.O.M.B.A.T. {combat@0.21.0 ENQUEUE_IMC}
		cfm-7.0.0-pre8-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre8 ENQUEUE_IMC}
		Corpse-Mod-1.14.4.jar Corpse {corpse@1.14.4-1.0.0 ENQUEUE_IMC}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 ENQUEUE_IMC}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 ENQUEUE_IMC}
		luckyblock-1.14.4-7.9.1.jar Lucky Block {lucky@7.9.1 ENQUEUE_IMC}
		MCFurnace-Mod-1.14.4.jar MCFurnace {mcfurnace@1.0 ENQUEUE_IMC}
		Morpheus-1.14.4-4.2.43.jar Morpheus {morpheus@version ENQUEUE_IMC}
		spiketraps-1.0.jar Spike Traps {spiketraps@1.0 ENQUEUE_IMC}
		SuperTools-1.5b.jar Super Tools {supertools@1.5b ENQUEUE_IMC}
		forge-1.14.4-28.0.82-universal.jar Forge {forge@28.0.82 ENQUEUE_IMC}
		forge-1.14.4-28.0.82-client.jar Minecraft {minecraft@1.14.4 ENQUEUE_IMC}
	Launched Version: 1.14.4-forge-28.0.82
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

**Comment by Stereowalker** [comment]
Your forge is outdated. Update forge to 1.14.4-28.0.107 so that it would work

**Comment by Trinova1** [comment]
Thank you very much !!!!
